#!/usr/bin/zsh
#   x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 xa xb xc xd xe xf
#0x       o
#1x 
#2x 
#3x 
#4x 
#5x 
#6x 
#7x 
#8x 
#9x 
#ax 
#bx 
#cx 
#dx 
#ex 
#fx 
#
#
#
#
##
# 0_1.5  line          xx -5 -7 0
# 0_2    line          xx -7 -5 0
# 0_2.5  line(default) xx -10 2 0
# 0_3    line          xx -5 -10 0
# 0_3    line          xx -5 -10 0
#
# 8.5_0	               xx 2 -23 0



#@ This is not success DANGER
function 0_1.5 () {
    # Done
    # xx -5 -7 0
    # OLD:python test.py --m01 " -5" --m02 " -7" --m03 "0"
    python test.py --m01 "85" --m02 "83" --m03 "0"
}

#@ This is not success DANGER
function 0_2 () {
    # Done
    # xx -7 -5 0
    # OLD:python test.py --m01 " -7" --m02 " -5" --m03 "0"
    python test.py --m01 "83" --m02 "85" --m03 "0"
}

#@ This is not success DANGER
function 0_2.5 () {
    # Done
    # 0_2.5  line(default) xx -10 2 0
    # OLD:python test.py --m01 " -10" --m02 "2" --m03 "0"
    python test.py --m01 "80" --m02 "92" --m03 "0"
}
# other  python test.py --m01 " -4" --m02 " -7" --m03 "0"

#@ This is not success DANGER
function 0_1 () {
    # Done
    # 0_1  line xx -5 -10 0
    # OLD:python test.py --m01 " -5" --m02 " -10" --m03 "0"
    python test.py --m01 "85" --m02 "80" --m03 "0"
}


#@ This is not success DANGER
function 0_0.5 () {
    #OLD:python test.py --m01 " -10" --m02 " -23" --m03 "0"
    python test.py --m01 "80" --m02 "67" --m03 "0"

}


#@ archive p8
function 3_0 () {
    # OLD:python test.py --m00_min "7" --m00_max "110" --m01 " -17" --m02 " 6" --m03 "0"
    #python test.py --m00_min "7" --m00_max "110" --m01 "73" --m02 "96" --m03 "0"
    python test.py --m00_min "7" --m00_max "110" --m01 "73" --m02 "89" --m03 "0"
}

#@ archive p7
function 3.5_0 () {
    # OLD:python test.py --m00_min "7" --m00_max "110" --m01 " -15" --m02 " 4" --m03 "0"
    #python test.py --m00_min "7" --m00_max "110" --m01 "75" --m02 "94" --m03 "0"
    python test.py --m00_min "7" --m00_max "110" --m01 "75" --m02 "88" --m03 "0"
}

#@ archive p6
function 4_0 () {
    # Done
    # OLD:python test.py --m00_min "7" --m00_max "110" --m01 " -12" --m02 " 0" --m03 "0"
    #python test.py --m00_min "7" --m00_max "110" --m01 "78" --m02 "90" --m03 "0"
    python test.py --m00_min "7" --m00_max "110" --m01 "78" --m02 "83" --m03 "0"
}

#@ archive p5
function 4.5_0 () {
    # OLD:python test.py --m00_min "10" --m00_max "100" --m01 " -10" --m02 " -3" --m03 "0"
    #python test.py --m00_min "10" --m00_max "100" --m01 "80" --m02 "87" --m03 "0"
    python test.py --m00_min "10" --m00_max "100" --m01 "80" --m02 "80" --m03 "0"
}

#@ archive p4
function 5_0 () { 
    # Done
    # 5_0 10~ -8 -5 0
    # OLD:python test.py --m00_min "10" --m00_max "100" --m01 " -8" --m02 " -5" --m03 "0"
    #python test.py --m00_min "10" --m00_max "100" --m01 "82" --m02 "85" --m03 "0"
    #python test.py --m00_min "10" --m00_max "100" --m01 "82" --m02 "80" --m03 "0"
    python test.py --m00_min "10" --m00_max "100" --m01 "82" --m02 "75" --m03 "0"
}

#@ archive p3
function 6_0 () { 
    # Done
    # 6_0 45 -5 -10 0
    # OLD:python test.py --m00_min "14" --m00_max "100" --m01 " -5" --m02 " -10" --m03 "0"
    python test.py --m00_min "14" --m00_max "100" --m01 "85" --m02 "70" --m03 "0"
}

#@ archive p2
function 7_0 () {
    # Done
    # 7_0 45 -3 -14 0
    # OLD:python test.py --m00_min "14" --m00_max "100" --m01 " -3" --m02 " -14" --m03 "0"
    python test.py --m00_min "17" --m00_max "100" --m01 "87" --m02 "68" --m03 "0"
}

#@ archive p1
function 8_0 () {
    # Done
    # 8_0 19~ -1 -18 0
    # OLD:python test.py --m00_min "19" --m00_max "100" --m01 " -1" --m02 " -18" --m03 "0"
    #python test.py --m00_min "19" --m00_max "100" --m01 "80" --m02 "65" --m03 "0"
    #python test.py --m00_min "19" --m00_max "100" --m01 "80" --m02 "60" --m03 "0"
    #python test.py --m00_min "19" --m00_max "100" --m01 "85" --m02 "60" --m03 "0"
    #python test.py --m00_min "19" --m00_max "100" --m01 "85" --m02 "64" --m03 "0"
    #python test.py --m00_min "19" --m00_max "100" --m01 "88" --m02 "67" --m03 "0"
    #python test.py --m00_min "19" --m00_max "100" --m01 "88" --m02 "64" --m03 "0"
    python test.py --m00_min "19" --m00_max "100" --m01 "88" --m02 "64" --m03 "3"
}

#@ archive base
function 8.5_0 () {
    # Done
    # 8.5_0 21~ 2 -23 0
    # OLD:python test.py --m00_min "21" --m00_max "100" --m01 " 3" --m02 " -23" --m03 "0"
    # New Done
    python test.py --m00_min "19" --m00_max "100" --m01 "93" --m02 "57" --m03 "0"
}

function line_base_m01 () {
    #python test.py --m00_min "19" --m00_max "100" --m01 "93" --m02 "57" --m03 "0"
    #python test.py --m00_min "19" --m00_max "100" --m01 "93" --m02 "50" --m03 "0"
    #python test.py --m00_min "19" --m00_max "100" --m01 "96" --m02 "50" --m03 "0"
    #python test.py --m00_min "24" --m00_max "100" --m01 "96" --m02 "50" --m03 "0"
    python test.py --m00_min "24" --m00_max "98" --m01 "96" --m02 "50" --m03 "0"
}

function line_base_m02 () {
    #python test.py --m00_min "24" --m00_max "98" --m01 "96" --m02 "45" --m03 "0"
    python test.py --m00_min "24" --m00_max "98" --m01 "96" --m02 "48" --m03 "0"
}

function line_base () {
    # Done
    8.5_0
}

function line_base_p01 () {
    # Done
    8_0
}

function line_base_p02 () {
    # Done
    7_0
}

function line_base_p03 () {
    # Done
    6_0
}

function line_base_p04 () {
    # Done
    5_0
}

function line_base_p05 () {
    # Done
    4.5_0
}

function line_base_p06 () {
    # Done
    4_0
}

function line_base_p07 () {
    # Done
    3.5_0
}

function line_base_p08 () {
    # Done
    3_0
}

function line_base_p09 () {
    # Done
    #python test.py --m00_min "7" --m00_max "110" --m01 "73" --m02 "89" --m03 "0"
    #python test.py --m00_min "7" --m00_max "110" --m01 "68" --m02 "89" --m03 "0"
    #python test.py --m00_min "7" --m00_max "110" --m01 "66" --m02 "93" --m03 "0"
    python test.py --m00_min "7" --m00_max "110" --m01 "66" --m02 "95" --m03 "0"
}

function line_base_p10 () {
    #python test.py --m00_min "7" --m00_max "110" --m01 "60" --m02 "104" --m03 "30"
    #python test.py --m00_min "7" --m00_max "110" --m01 "60" --m02 "101" --m03 "30"
    #python test.py --m00_min "0" --m00_max "110" --m01 "62" --m02 "101" --m03 "30"
    python test.py --m00_min "0" --m00_max "130" --m01 "62" --m02 "101" --m03 "30"
}


function line_base_p11 () {
    #python test.py --m00_min "7" --m00_max "110" --m01 "66" --m02 "95" --m03 "0"
    #python test.py --m00_min "7" --m00_max "110" --m01 "60" --m02 "95" --m03 "0"
    #python test.py --m00_min "7" --m00_max "110" --m01 "60" --m02 "102" --m03 "0"
    #python test.py --m00_min "7" --m00_max "110" --m01 "60" --m02 "104" --m03 "0"
    #python test.py --m00_min "0" --m00_max "130" --m01 "60" --m02 "104" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "130" --m01 "60" --m02 "104" --m03 "0"
    python test.py --m00_min " -10" --m00_max "128" --m01 "60" --m02 "104" --m03 "0"
}

function line_base_p12 () {
    #python test.py --m00_min " -10" --m00_max "128" --m01 "50" --m02 "114" --m03 "0"
    python test.py --m00_min " -10" --m00_max "128" --m01 "56" --m02 "107" --m03 "0"
}

function line_base_p13 () {
    #python test.py --m00_min " -10" --m00_max "128" --m01 "60" --m02 "104" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "128" --m01 "50" --m02 "104" --m03 "0"
    python test.py --m00_min " -10" --m00_max "128" --m01 "50" --m02 "114" --m03 "0"
}

function line_base_p14 () {
    #python test.py --m00_min " -10" --m00_max "120" --m01 "45" --m02 "115" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "45" --m02 "117" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "45" --m02 "117" --m03 "30"
    python test.py --m00_min "0" --m00_max "120" --m01 "45" --m02 "117" --m03 "30"
}

function line_base_p15 () {
    #python test.py --m00_min " -10" --m00_max "128" --m01 "50" --m02 "114" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "125" --m01 "45" --m02 "114" --m03 "0"
    python test.py --m00_min " -10" --m00_max "120" --m01 "45" --m02 "120" --m03 "0"
}

function line_base_p16 () {
    #python test.py --m00_min " -10" --m00_max "120" --m01 "35" --m02 "120" --m03 "0"
    python test.py --m00_min " -10" --m00_max "120" --m01 "35" --m02 "127" --m03 "0"
}

function line_base_p17 () {
    python test.py --m00_min " -10" --m00_max "120" --m01 "30" --m02 "130" --m03 "0"
}

function line_base_p18 () {
    #python test.py --m00_min " -10" --m00_max "120" --m01 "30" --m02 "133" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "25" --m02 "133" --m03 "0"
    python test.py --m00_min " -10" --m00_max "120" --m01 "25" --m02 "135" --m03 "0"
}


function line_base_p19 () {
    #python test.py --m00_min " -10" --m00_max "120" --m01 "18" --m02 "140" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "16" --m02 "140" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "13" --m02 "140" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "13" --m02 "142" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "9" --m02 "146" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "9" --m02 "144" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "6" --m02 "144" --m03 "0"
    #python test.py --m00_min " -10" --m00_max "120" --m01 "4" --m02 "144" --m03 "0"
    python test.py --m00_min " -10" --m00_max "120" --m01 "4" --m02 "146" --m03 "0"
}


function test () {
    # OLD:python test.py --m00_min "7" --m00_max "110" --m01 " -24" --m02 " 6" --m03 "0"
    python test.py --m00_min "7" --m00_max "110" --m01 "66" --m02 "96" --m03 "0"
}


function stable () {
    # OLD:python test.py --m01 " -20" --m02 "0"
    python test.py --m01 "70" --m02 "90"
    #python test.py --m01 " -10" --m02 " -23" --m03 "0"

}

function stop () {
    #52 93 57 0
    python test.py --stop
}






function pos_maker () {
    local -a posff=(00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f \
     		    10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f \
     		    20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f \
     		    30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f \
     		    40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f \
     		    50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f \
     		    60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f \
     		    70 71 72 73 74 75 76 77 78 79 7a 7b 7c 7d 7e 7f \
     		    80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f \
     		    90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f \
     		    a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af \
     		    b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 ba bb bc bd be bf \
     		    c0 c1 c2 c3 c4 c5 c6 c7 c8 c9 ca cb cc cd ce cf \
     		    d0 d1 d2 d3 d4 d5 d6 d7 d8 d9 da db dc dd de df \
     		    e0 e1 e2 e3 e4 e5 e6 e7 e8 e9 ea eb ec ed ee ef \
     		    f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 fa fb fc fd fe ff)

    for pf in $posff; do
        #echo $pf
        sed -e "s/xx/$pf/g" base.py > pos/pos_$pf.py
	#echo "Hello World" | sed -e "s/ /,/g"
    done
}


#pos_maker

eval $@
